# This is a basic workflow to help you get started with Actions

name: zzuClock

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 18 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: install imports
        run: |
          pip install -r requirements.txt
          
      - name: Working
        env:
            uid: ${{secrets.uid}}
            upw: ${{secrets.upw}}
            email: ${{secrets.email}}
            city: ${{secrets.city}}
        run: python clock.py
